-- Add referral tracking: records which existing user (if any) referred
-- a new signup, captured from a /register?ref=<user_id> link generated by
-- the ShareButton on the Dashboard.
ALTER TABLE users ADD COLUMN referred_by uuid REFERENCES users(id);
CREATE INDEX idx_users_referred_by ON users(referred_by);
